name: Trigger workflow on receiver repo

on:
  push:
    branches:
      - main
 
jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    
    env:
      REPO_OWNER: Liz2310
      REPO_NAME: receiver
      WORKFLOW_FILENAME: receiver.yaml
      
    steps:
    - name: trigger-workflow
      run: |
        curl -X POST \
        -H "Authorization: Bearer ${{secrets.GHA_TOKEN}}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/REPO_OWNER/REPO_NAME/actions/workflows/WORKFLOW_FILENAME/dispatches \
        -d '{"ref": "main"}'
