name: Trigger workflow on receiver repo

on:
  push:
    branches:
      - main
 
jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: trigger-workflow
      run: |
        curl -X POST \
        -H "Authorization: Bearer ${{secrets.GHA_TOKEN}}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/Liz2310/receiver/actions/workflows/receiver.yaml/dispatches \
        -d '{"ref": "main"}'
