name: Trigger workflow on receiver repo

on:
  push:
    branches:
      - main
 
jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: Liz2310
        repo: receiver
        github_token: ${{ secrets.GHA_TOKEN }}
        workflow_file_name: receiver.yaml


    # - name: trigger-workflow
      # run: |
      #   curl -X POST \
      #   -H "Authorization: Bearer ${{secrets.GHA_TOKEN}}" \
      #   -H "Accept: application/vnd.github.v3+json" \
      #   https://api.github.com/repos/Liz2310/receiver/actions/workflows/receiver.yaml/dispatches \
      #   -d '{"ref": "main"}'

